# Generated by Django 2.2.13 on 2020-07-16 15:39

from django.db import migrations, models
import django.db.models.deletion
import site_operation.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20200623_1320'),
        ('site_operation', '0002_indeximage_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=1000, verbose_name='Type name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='promotion')),
                ('activation', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=1000, verbose_name='Publish status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_page', to='books.Book', verbose_name='book')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_content', to='site_operation.ContentType', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImagePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000, verbose_name='alt text')),
                ('book_image', models.ImageField(default='media/image/default.png', max_length=1000, upload_to=site_operation.models.image_upload_path, verbose_name='Book image')),
                ('activation', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=1000, verbose_name='Publish status')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_image_book', to='books.Book', verbose_name='book')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='site_operation.ContentType', verbose_name='Type')),
            ],
        ),
    ]
