# Generated by Django 3.0.2 on 2020-03-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0007_remove_book_book_author'),
        ('users', '0015_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Reader', verbose_name='User bookcase')),
            ],
            options={
                'verbose_name': 'Bookcase',
                'verbose_name_plural': 'Bookcase',
            },
        ),
    ]
