# Generated by Django 3.0.2 on 2020-03-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookcase',
            table='Bookcase',
        ),
    ]
