# Generated by Django 2.2.4 on 2020-04-20 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0002_auto_20200302_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User bookcase'),
        ),
    ]
