# Generated by Django 2.2.4 on 2020-04-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0004_auto_20200424_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcase',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book'),
        ),
    ]
