# Generated by Django 2.2.10 on 2020-06-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200529_1739'),
        ('bookshelves', '0005_auto_20200425_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='added time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_book', to='books.Book', verbose_name='book')),
                ('bookcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_mark', to='bookshelves.Bookcase', verbose_name='bookcase')),
            ],
        ),
    ]
