# Generated by Django 2.2.10 on 2020-06-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200529_1739'),
        ('bookshelves', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark'},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marked_chpater', to='books.Chapter', verbose_name='book'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('bookcase', 'chapter')},
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='Bookmark',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='book',
        ),
    ]
