# Generated by Django 2.2.10 on 2020-06-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200529_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelves', '0008_auto_20200621_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_book', to='books.Book', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_marked', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_chapter', to='books.Chapter', verbose_name='Chapter'),
        ),
    ]
