# Generated by Django 2.2.10 on 2020-06-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0010_remove_bookcase_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='chapter',
        ),
    ]
