# Generated by Django 2.2.10 on 2020-06-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_remove_book_favoured'),
        ('bookshelves', '0011_auto_20200621_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcase',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_chapter', to='books.Chapter', verbose_name='Chapter'),
        ),
    ]
