# Generated by Django 2.2.13 on 2020-08-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], default='Normal', max_length=100, verbose_name='Account status')),
                ('valid_date', models.DateTimeField(verbose_name='Valid date')),
                ('level', models.IntegerField(default=0, max_length=3, verbose_name='VIP level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Over time'), ('WAIT_BUYER_PAY', 'Trade create'), ('TRADE_FINISHED', 'Trade close'), ('paying', 'Wait for payment')], default='paying', max_length=30, verbose_name='order status')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='payment time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
