# Generated by Django 2.2.13 on 2020-08-15 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0002_auto_20200813_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Over time'), ('WAIT_BUYER_PAY', 'Trade create'), ('TRADE_FINISHED', 'Trade close'), ('paying', 'Wait for payment')], default='paying', max_length=30, verbose_name='order status')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='payment time')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
            ],
        ),
        migrations.CreateModel(
            name='VipCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=200, unique=True, verbose_name='Vip combo')),
                ('description', models.TextField(max_length=10000, verbose_name='Combo description')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('length', models.IntegerField(default=0, verbose_name='Length')),
            ],
        ),
        migrations.AddField(
            model_name='userstatus',
            name='bookshelf_coin',
            field=models.FloatField(default=0.0, verbose_name='Bookshelf coin'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='user exp'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='month_ticket',
            field=models.IntegerField(default=0, verbose_name='Monthly ticket'),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.AddField(
            model_name='payment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='trade.VipCombo', verbose_name='Combo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
