# Generated by Django 2.2.4 on 2019-12-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0003_auto_20191208_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Reader', verbose_name='User bookcase')),
            ],
            options={
                'verbose_name': 'Bookcase',
                'verbose_name_plural': 'Bookcase',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
