# Generated by Django 3.0.2 on 2020-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcase',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added time'),
        ),
    ]
