# Generated by Django 2.2.4 on 2019-12-08 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_vip', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='Normal', editable=False, max_length=10, verbose_name='Vip status')),
                ('vip_validate', models.DateField(default='', editable=False, null=True, verbose_name='Validate Until')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_reader', to='users.Profile')),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Reader',
                'db_table': 'Reader',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
                'db_table': 'Author',
            },
        ),
    ]
