# Generated by Django 2.2.4 on 2019-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Author', 'Author'), ('Editor', 'Editor'), ('Admin', 'Admin')], default='Admin', max_length=150, verbose_name='Role'),
        ),
    ]
