# Generated by Django 2.2.4 on 2019-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contract_number',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Contact number'),
        ),
    ]
