# Generated by Django 2.2.4 on 2019-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact number'),
        ),
    ]
