# Generated by Django 2.2.4 on 2019-11-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reader_user_birthday'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
