# Generated by Django 2.2.4 on 2019-11-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191108_1417'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
