# Generated by Django 3.0.2 on 2020-01-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_mobile',
        ),
    ]
