# Generated by Django 3.0.2 on 2020-01-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_role',
            new_name='role',
        ),
    ]
