# Generated by Django 2.2.4 on 2019-11-15 13:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191108_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user_birthday',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user_gender',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user_icon',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user_mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='user_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=150, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(default='media/image/default.png', max_length=1000, null=True, upload_to='media/image/%Y/%m', verbose_name='User icon'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Mobile'),
        ),
    ]
