# Generated by Django 3.0.2 on 2020-01-29 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='is_user_vip',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='Normal', max_length=10, verbose_name='Vip status'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='users.Profile', verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
                'db_table': 'Author',
            },
        ),
    ]
