# Generated by Django 3.0.2 on 2020-01-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200129_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='is_user_vip',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10, verbose_name='Vip status'),
        ),
    ]
