# Generated by Django 2.2.4 on 2020-02-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200129_1254'),
        ('users', '0003_auto_20191208_2108'),
    ]

    operations = [
    ]
