# Generated by Django 2.2.4 on 2020-02-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20200212_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contract_number',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_user_vip',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10, verbose_name='Vip status'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='users.Profile', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='vip_validate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Validate Until'),
        ),
    ]
