# Generated by Django 3.0.2 on 2020-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200212_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact number'),
        ),
    ]
