# Generated by Django 3.0.2 on 2020-03-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_book_author'),
        ('users', '0014_auto_20200227_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='books.Book'),
        ),
    ]
