# Generated by Django 3.0.2 on 2020-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Author', 'Author'), ('Editor', 'Editor'), ('Admin', 'Admin')], default='Admin', max_length=150, verbose_name='Role'),
        ),
    ]
