# Generated by Django 3.0.2 on 2020-03-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200309_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.RemoveField(
            model_name='author',
            name='contract_number',
        ),
    ]
