# Generated by Django 2.2.4 on 2020-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200310_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='data_line',
            field=models.CharField(default='one', max_length=10, verbose_name='vvv'),
        ),
    ]
