# Generated by Django 2.2.4 on 2020-05-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200504_2306'),
        ('users', '0018_author_data_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
