# Generated by Django 2.2.13 on 2020-08-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0027_auto_20200623_1320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='Content')),
                ('like_num', models.IntegerField(default=0, verbose_name='Liked_vote')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='books.Book', verbose_name='Book')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='user_operation.UserComment', verbose_name='Parent message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User comment',
                'verbose_name_plural': 'User comment',
            },
        ),
    ]
