# Generated by Django 2.2.13 on 2020-08-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='like_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='Liked_vote'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='parent index', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='user_operation.UserComment', verbose_name='Parent message'),
        ),
    ]
