# Generated by Django 2.2.13 on 2020-08-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20200804_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='parent_comment',
            new_name='sub_comment',
        ),
    ]
