# Generated by Django 2.2.4 on 2019-11-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=30, verbose_name='Book name')),
                ('book_short_description', models.TextField(verbose_name='Short descritpion')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
            options={
                'verbose_name': 'Novel',
                'verbose_name_plural': 'Novel',
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=30, verbose_name='Category name')),
                ('category_code', models.CharField(default='', max_length=30, verbose_name='Category code')),
                ('category_type', models.IntegerField(choices=[(1, 'Primary type'), (2, 'Secondary genre')], verbose_name='Category Type')),
                ('is_tab', models.BooleanField(default=False, verbose_name='is Navigate')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Added time')),
                ('total_number', models.BigIntegerField(default=0, verbose_name='Total Number')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='books.BookCategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Type Category',
                'verbose_name_plural': 'Type Category',
                'db_table': 'Book Genre',
            },
        ),
    ]
