# Generated by Django 2.2.4 on 2019-11-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='users.Author'),
        ),
    ]
