# Generated by Django 3.0.2 on 2020-02-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200212_1817'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_added',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='users.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='', verbose_name='Book Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', max_length=30, upload_to='', verbose_name='Book image'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=150, verbose_name='Book Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_type', to='books.BookCategory', verbose_name='book type'),
        ),
        migrations.AddField(
            model_name='book',
            name='chapter_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Chapter Count'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_click',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Click'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_vote',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total vote'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_words',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total_words'),
        ),
        migrations.AddField(
            model_name='book',
            name='weekly_vote',
            field=models.IntegerField(default=0, editable=False, verbose_name='Weekly vote'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_short_description',
            field=models.TextField(default='', verbose_name='Short description'),
        ),
    ]
