# Generated by Django 2.2.4 on 2019-11-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reader_user_birthday'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=30, verbose_name='Book name')),
                ('book_short_description', models.TextField(verbose_name='Short descritpion')),
                ('book_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='users.Author')),
            ],
        ),
    ]
