# Generated by Django 3.0.2 on 2020-02-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200227_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Book name'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(default='', max_length=150, verbose_name='Chapter title')),
                ('chapter_body', models.TextField(default='', verbose_name='Chapter text')),
                ('word_count', models.IntegerField(default=0, verbose_name='Word count')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('publish_status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Published', max_length=150)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book id')),
            ],
        ),
    ]
