# Generated by Django 3.0.2 on 2020-03-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200227_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category_type',
            field=models.IntegerField(default='', verbose_name='Category Type'),
        ),
    ]
