# Generated by Django 2.2.4 on 2019-11-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191108_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Novel', 'verbose_name_plural': 'Novel'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
