# Generated by Django 3.0.2 on 2020-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200302_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='total_number',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='Total Number'),
        ),
    ]
