# Generated by Django 3.0.2 on 2020-03-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200302_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book_id',
        ),
        migrations.AddField(
            model_name='book',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='Chapter'),
        ),
    ]
