# Generated by Django 3.0.2 on 2020-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fav_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total favorite number'),
        ),
    ]
