# Generated by Django 2.2.4 on 2020-03-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_fav_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Chapter'),
        ),
    ]
