# Generated by Django 2.2.4 on 2020-05-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_author_data_line'),
        ('books', '0010_auto_20200408_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='users.Author', verbose_name='author'),
        ),
    ]
