# Generated by Django 2.2.4 on 2020-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200511_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='publish_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Unpublished', 'Unpublished')], default='Published', max_length=150),
        ),
    ]
