# Generated by Django 2.2.4 on 2020-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200516_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
    ]
