# Generated by Django 2.2.4 on 2020-05-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200520_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'Type Category', 'verbose_name_plural': 'Type categories'},
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='total_number',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_books', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.BookCategory', verbose_name='book type'),
        ),
    ]
