# Generated by Django 2.2.4 on 2020-05-29 16:08

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200525_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', max_length=30, upload_to=books.models.image_upload_path, verbose_name='Book image'),
        ),
    ]
