# Generated by Django 2.2.4 on 2020-05-29 16:39

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200529_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='media/image/default.png', max_length=1000, upload_to=books.models.image_upload_path, verbose_name='Book image'),
        ),
    ]
