# Generated by Django 2.2.10 on 2020-06-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200529_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'chapter', 'verbose_name_plural': 'chapters'},
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='Chapter',
        ),
    ]
