# Generated by Django 2.2.10 on 2020-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0011_auto_20200621_2243'),
        ('books', '0022_auto_20200621_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favoured',
            field=models.ManyToManyField(related_name='favoured_book', to='bookshelves.Bookcase', verbose_name='Book'),
        ),
    ]
