# Generated by Django 2.2.10 on 2020-06-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0011_auto_20200621_2243'),
        ('books', '0023_book_favoured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favoured',
        ),
        migrations.AddField(
            model_name='book',
            name='favoured',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favoured_book', to='bookshelves.Bookcase', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
