# Generated by Django 2.2.10 on 2020-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_remove_book_favoured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='last update'),
        ),
    ]
